spring.application.name=aluminiNetwork
spring.data.mongodb.uri = mongodb://localhost:27017/aluminiNetwork
server.port = 9001
spring.data.mongodb.auto-index-creation=true
JWT_SECRET_KEY=${env.JWT_SECRET_KEY}