spring.application.name=aluminiNetwork
spring.data.mongodb.database=aluminiCluster
spring.data.mongodb.uri = mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@aluminicluster.vt0b8yw.mongodb.net/?retryWrites=true&w=majority&appName=aluminiCluster
server.port = 9001
spring.data.mongodb.auto-index-creation=true
JWT_SECRET_KEY=${env.JWT_SECRET_KEY}